root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/tumux"
  cmd = "go build -o ./tmp/tumux ./cmd/tumux"
  delay = 500
  exclude_dir = ["tmp", "vendor", ".git", ".github"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  send_interrupt = true
  kill_delay = 500

[misc]
  clean_on_exit = true
